export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const END_AJAX_CALL = "END_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";
export const AJAX_CALL_CLEAR = "AJAX_CALL_CLEAR";

export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
export const SET_SUCCESS_MESSAGE = "SET_SUCCESS_MESSAGE";
export const SET_LOADING_STATE = "SET_LOADING_STATE";
